/**
 * Final-apply pipeline for the loudnessShaper node: 4× oversample →
 * LUT lookup → 4× downsample with anti-aliasing.
 *
 * Per design-loudness-shaper §"Pipeline shape" — the 4× oversample
 * exists to absorb harmonics generated by the non-linear LUT before
 * they alias back into the audible band. Used once per render after
 * the iteration loop has converged on a winning curve; not used during
 * iteration (which runs at base rate per the design's accepted
 * iteration-bias tradeoff).
 *
 * Implementation note (decision authority exercised at Phase 4): uses
 * the restored `Oversampler.oversample(input, fn)` convenience method
 * rather than calling `upsample` / `downsample` separately. The class's
 * `oversample` already preserves input.length on output (factor 4 →
 * `length × 4 → fn-per-sample → length / 4 = length`), so no filter-
 * latency padding is required at this layer. The Oversampler's biquad
 * lowpass introduces a small warm-up transient on the leading samples
 * — the same transient the existing oversample round-trip null test
 * accepts as the price of doing simple anti-aliasing. The
 * identity-LUT round-trip test below matches that test's tolerance
 * convention (check the settled second half).
 *
 * One Oversampler instance per channel. Each instance owns its own
 * upsample / downsample biquad state; channels do not share filter
 * state. The Oversampler is stateful but for an offline single-buffer
 * apply we call `oversample` once per channel on the entire buffer.
 */

import { Oversampler, type OversamplingFactor } from "@e9g/buffered-audio-nodes-utils";
import { type LUT, lookupLUT } from "./lut";

/**
 * Default and only currently-used oversampling factor. The design
 * specifies 4×; the type still allows the wider Oversampler-supported
 * set (1/2/4/8) so callers in other contexts can override if they ever
 * need to.
 */
const DEFAULT_FACTOR: OversamplingFactor = 4;

export interface ApplyFinalArgs {
	source: ReadonlyArray<Float32Array>;
	sampleRate: number;
	lut: LUT;
	factor?: OversamplingFactor;
}

/**
 * Apply `lut` to each channel of `source` through the 4× oversample
 * pipeline. Returns a fresh `Float32Array[]` with one new array per
 * input channel; output length per channel equals input length per
 * channel (the Oversampler's `oversample` method preserves length at
 * any factor).
 */
export function applyFinal(args: ApplyFinalArgs): Array<Float32Array> {
	const { source, sampleRate, lut, factor = DEFAULT_FACTOR } = args;

	const output: Array<Float32Array> = [];

	for (let channelIndex = 0; channelIndex < source.length; channelIndex++) {
		const channel = source[channelIndex];

		if (channel === undefined || channel.length === 0) {
			output.push(new Float32Array(0));
			continue;
		}

		const oversampler = new Oversampler(factor, sampleRate);
		const transformed = oversampler.oversample(channel, (sample) => lookupLUT(lut, sample));

		output.push(transformed);
	}

	return output;
}
