/**
 * Final-apply step for the loudnessShaper node: per-chunk oversample →
 * per-sample curve evaluation at 4× rate → downsample. Per
 * design-loudness-shaper §"Pipeline shape" — the 4× oversample exists
 * to absorb harmonics generated by the non-linear curve before they
 * alias back into the audible band.
 *
 * Per-channel processing throughout: each channel sample's sign picks
 * `posParams` or `negParams` and the curve `f(x, boost, posParams,
 * negParams)` runs directly on that sample. No envelope, no linked
 * detection, no smoothing — the shaper is sample-instantaneous,
 * memoryless waveshaping.
 *
 * Memory discipline (per design-transforms §"Memory discipline"): this
 * module never allocates source-sized arrays. Per-chunk allocation:
 * `chunkLen × factor × 4 bytes` of upsampled scratch + `chunkLen × 4
 * bytes` of downsampled output per channel. Bounded by chunk size, not
 * source size.
 *
 * The per-channel `Oversampler` instances are owned by the caller (the
 * stream class allocates them once in `_process` and reuses them across
 * `_unbuffer` calls). Their biquad states persist across chunks so
 * chunk boundaries are continuous in the AA filter response — multi-
 * chunk runs match single-chunk runs.
 */

import type { Oversampler, OversamplingFactor } from "@e9g/buffered-audio-nodes-utils";
import type { CurveParams } from "./curve";
import { f } from "./curve";

/**
 * Default and only currently-used oversampling factor. The design
 * specifies 4×; the type still allows the wider Oversampler-supported
 * set (1/2/4/8) so callers in other contexts can override if they ever
 * need to.
 */
export const DEFAULT_FACTOR: OversamplingFactor = 4;

export interface ApplyFinalChunkArgs {
	chunkSamples: ReadonlyArray<Float32Array>;
	boost: number;
	posParams: CurveParams;
	negParams: CurveParams;
	/** One persistent `Oversampler` per channel. State carries across chunks. */
	oversamplers: ReadonlyArray<Oversampler>;
}

/**
 * Per-chunk final apply: for each channel, run the persistent
 * `Oversampler.oversample(channel, x => f(x, boost, posParams,
 * negParams))` — upsample → per-sample curve → downsample. Returns a
 * fresh `Float32Array[]` (one per channel) with each per-channel array
 * length equal to the input chunk's per-channel length.
 *
 * The oversampler instances are persistent across chunks (their biquad
 * states carry the AA filter continuity), so multi-chunk runs match
 * the single-chunk path.
 */
export function applyFinalChunk(args: ApplyFinalChunkArgs): Array<Float32Array> {
	const { chunkSamples, boost, posParams, negParams, oversamplers } = args;
	const channelCount = chunkSamples.length;

	if (channelCount === 0) return [];

	const output: Array<Float32Array> = [];

	for (let channelIndex = 0; channelIndex < channelCount; channelIndex++) {
		const channel = chunkSamples[channelIndex];
		const oversampler = oversamplers[channelIndex];

		if (channel === undefined || oversampler === undefined || channel.length === 0) {
			output.push(new Float32Array(channel?.length ?? 0));
			continue;
		}

		const transformed = oversampler.oversample(channel, (x) => f(x, boost, posParams, negParams));

		output.push(transformed);
	}

	return output;
}
